#!/bin/bash
# set the STRING variable
export IOTHUB_DEVICE_SECURITY_TYPE=""
export IOTHUB_DEVICE_DPS_ENDPOINT=""
export IOTHUB_DEVICE_DPS_ID_SCOPE=""
export IOTHUB_DEVICE_DPS_DEVICE_ID=""
export IOTHUB_DEVICE_DPS_DEVICE_KEY=""
export IOTHUB_DEVICE_CONNECTION_STRING=""
# print the contents of the variable on screen
echo $IOTHUB_DEVICE_SECURITY_TYPE
echo $IOTHUB_DEVICE_DPS_ENDPOINT
echo $IOTHUB_DEVICE_DPS_ID_SCOPE
echo $IOTHUB_DEVICE_DPS_DEVICE_ID
echo $IOTHUB_DEVICE_DPS_DEVICE_KEY
echo $IOTHUB_DEVICE_CONNECTION_STRING

pip install -r requirememts.txt
python -i main.py
